// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjXyYeJ7SlizOLhWduGYMD4bd4hHbmGaY',
    appId: '1:802289116887:web:42870334ed040b24407292',
    messagingSenderId: '802289116887',
    projectId: 'react-flutter-golang',
    authDomain: 'react-flutter-golang.firebaseapp.com',
    storageBucket: 'react-flutter-golang.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdSP0Wsk4DqaMBSY4tjkvUItqzUh-fU-8',
    appId: '1:802289116887:android:2aa145f9f25424cd407292',
    messagingSenderId: '802289116887',
    projectId: 'react-flutter-golang',
    storageBucket: 'react-flutter-golang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdVjXJb5Wi9A376c9eGwIj76TTkXY4V2c',
    appId: '1:802289116887:ios:73380c246bef1669407292',
    messagingSenderId: '802289116887',
    projectId: 'react-flutter-golang',
    storageBucket: 'react-flutter-golang.appspot.com',
    iosClientId: '802289116887-eejt5f6vqt9lvbgriadv6ii48b7ojjfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdVjXJb5Wi9A376c9eGwIj76TTkXY4V2c',
    appId: '1:802289116887:ios:73380c246bef1669407292',
    messagingSenderId: '802289116887',
    projectId: 'react-flutter-golang',
    storageBucket: 'react-flutter-golang.appspot.com',
    iosClientId: '802289116887-eejt5f6vqt9lvbgriadv6ii48b7ojjfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMobileApp',
  );
}
